#!/bin/bash

# save this file to either /etc/caudecrc or ~/.caudecrc

# CAUDECDIR="" # set to a directory of your choosing (e.g. ${HOME}/tmp)

# default compression levels (try 'caudec -c CODEC -q help' for a full list of possible values)
compression_FLAC=5 # 0-8
compression_WavPack=g # [f|g|h|hh][x[1-6]]
bitrate_WavPackLossy=320 # 2.9-23.9 or 24-9600
compression_MonkeysAudio=2 # 1-5
compression_lossyWAV=S # X, P, C, S, H, E, I
compression_Musepack=5 # 0-10

compression_LAME=2 # 0-9, used with LAME_MODE='VBR'
bitrate_LAME=320 # 16-320, used with LAME_MODE='CBR'
average_bitrate_LAME=256 # 8-310, used with LAME_MODE='ABR'
LAME_MODE='VBR' # 'VBR' (variable bitrate), 'CBR' (constant bitrate) or 'ABR' (average bitrate)
ID3Padding=512 # size in bytes of padding to add to ID3v2 tags

compression_OggVorbis=5 # 0-10, used with OggVorbis_MODE='VBR'
bitrate_OggVorbis=256 # 32-500, used with OggVorbis_MODE='CBR'
average_bitrate_OggVorbis=256 # 32-500, used with OggVorbis_MODE='ABR'
OggVorbis_MODE='VBR' # 'VBR' (variable bitrate), 'CBR' (constant bitrate) or 'ABR' (average bitrate)

compression_Opus=96 # 6-320, used with Opus_MODE='VBR'
bitrate_Opus=96 # 6-320, used with Opus_MODE='CBR'
average_bitrate_Opus=96 # 6-320, used with Opus_Mode='ABR'
Opus_MODE='VBR' # 'VBR' (variable bitrate), 'CBR' (constant bitrate) or 'ABR' (average bitrate)

setCoverArtworkFileByDefault="" # embed this file in all supported files as cover art
setCoverArtworkFileForLosslessByDefault="" # embed this file in all supported lossless files as cover art
setCoverArtworkFileForLossyByDefault="" # embed this file in all supported lossy files as cover art

copyOtherFilesByDefault="" # copy certain files when transcoding to lossless (see caudec -h for format)
copyOtherFilesForLosslessByDefault="" # copy certain files when transcoding to lossless (see caudec -h for format)
copyOtherFilesForLossyByDefault="" # copy certain files when transcoding to lossy (see caudec -h for format)

maxInstances=1 # maximum number of caudec instances allowed to run concurrently
maxInputFiles=100 # raise a warning and exit if the number of input files is higher than that
preloadSources=false # cache source files to temporary directory (e.g. a fast SSD) before processing them
preventClipping=true # reduce volume to prevent clipping, when resampling or applying gain
setCompilationFlagWithAlbumArtist=false # always true when ALBUMARTIST="Various Artists" regardless of this setting
keepWavMetadata=false # set to true to keep WAV metadata with FLAC and WavPack
tagCompressionSetting=true # store the compression setting in metadata
ignoreUnsupportedFiles=false # set to true to prevent caudec from aborting when some of the input files are unsupported
hashes='' # comma separated list of hashes to compute and tag (CRC32, MD5, SHA1, SHA256 and / or SHA512)
enableColors=true # Enable colors in human-readable output
useBrightColors=true # If enableColors=true, use bright colors (instead of darker ones)

# Whitelist / Blacklist: lists of comma separated tags
# Example: 'artist, date, album, tracknumber, title, genre, replaygain_reference_loudness, replaygain_track_gain, replaygain_track_peak, replaygain_album_gain, replaygain_album_peak'
# Tags in those lists are case-insensitive and format-agnostic.
# Example: 'albumartist' will match both 'ALBUMARTIST' and 'Album Artist'; 'organization' will match 'ORGANIZATION' and 'Label'.

# Current list of tag name variations:
# albumartist <---> album artist
# date <---> year
# description <---> comment
# discnumber <---> disc
# disctotal <---> totaldiscs
# labelno <---> catalog
# location <---> record location
# organization <---> label
# sourcemedia <---> media
# tracknumber <---> track
# tracktotal <---> totaltracks

# tagWhitelist: tags to keep when transcoding (all others are discarded - inactive if empty)
tagWhitelist=''

# tagBlacklist: tags to discard when transcoding (all others are kept - inactive when empty, and when tagWhitelist is non-empty)
tagBlacklist=''
