#!/bin/bash

# save this file to either /etc/caudecrc or ~/.caudecrc

# CAUDECDIR="" # set to a directory of your choosing (e.g. ${HOME}/tmp)

# default compression levels (try 'caudec -c CODEC -q help' for a full list of possible values)
compression_FLAC=5 # 0-8
compression_lossyWAV=S # X, P, C, S, H, E, I
compression_MonkeysAudio=2 # 1-5
compression_WavPack=gx1 # [f|g|h|hh][x[1-6]]
average_bitrate_WavPackLossy=256 # 2.9-23.9 or 24-9600

bitrate_AAC=128 # 8-320, always average bitrate
average_bitrate_AAC=128 # 8-320, always average bitrate
AAC_MODE='ABR' # 'ABR' (average bitrate) or 'CBR' (constant bitrate)

compression_MP3=3 # 0-9, used with MP3_MODE='VBR'
bitrate_MP3=128 # 16-320, used with MP3_MODE='CBR'
average_bitrate_MP3=256 # 8-310, used with MP3_MODE='ABR'
MP3_MODE='VBR' # 'VBR' (variable bitrate), 'ABR' (average bitrate) or 'CBR' (constant bitrate)
ID3Padding=512 # size in bytes of padding to add to ID3v2 tags

compression_OggVorbis=3 # 0-10, used with OggVorbis_MODE='VBR'
bitrate_OggVorbis=96 # 32-500, used with OggVorbis_MODE='CBR'
average_bitrate_OggVorbis=96 # 32-500, used with OggVorbis_MODE='ABR'
OggVorbis_MODE='VBR' # 'VBR' (variable bitrate), 'ABR' (average bitrate) or 'CBR' (constant bitrate)

compression_Opus=96 # 6-320, used with Opus_MODE='VBR'
bitrate_Opus=96 # 6-320, used with Opus_MODE='CBR'
average_bitrate_Opus=96 # 6-320, used with Opus_Mode='ABR'
Opus_MODE='VBR' # 'VBR' (variable bitrate), 'ABR' (average bitrate) or 'CBR' (constant bitrate)

# Default destination is the current directory. This can be overridden by the following destinations variables:

# output to this directory by default (implies -P "$defaultDestination")
# example: defaultDestination="${HOME}/Music"
# !!! All codecs will go there, unless overridden by -o/-O/-P
defaultDestination=""

# output to this directory by default for lossless codecs (implies -P "$defaultLosslessDestination")
# example: defaultLosslessDestination="${HOME}/Music/FLAC"
# !!! All lossless codecs will go there, unless overridden by -o/-O/-P
defaultLosslessDestination=""

# output to this directory by default for lossy codecs (implies -P "$defaultLossyDestination")
# example: defaultLossyDestination="${HOME}/Music/MP3"
# !!! All lossy codecs will go there, unless overridden by -o/-O/-P
defaultLossyDestination=""

# put linked WavPack Hybrid files there by default; will be overridden by -l
# example: defaultLosslessDestination="${HOME}/Music/WavPack/lossless"
# example: defaultLinkedDestination="${HOME}/Music/WavPack/lossy"
# !!! set defaultLosslessDestination sensibly if your lossless and lossy collection is just WavPackHybrid
defaultLinkedDestination=""

setCoverArtworkFileByDefault="" # embed this file in all supported files as cover art
setCoverArtworkFileForLosslessByDefault="" # embed this file in all supported lossless files as cover art
setCoverArtworkFileForLossyByDefault="" # embed this file in all supported lossy files as cover art

copyOtherFilesByDefault="" # copy certain files when transcoding to lossless (see caudec -h for format)
copyOtherFilesForLosslessByDefault="" # copy certain files when transcoding to lossless (see caudec -h for format)
copyOtherFilesForLossyByDefault="" # copy certain files when transcoding to lossy (see caudec -h for format)

maxInstances=1 # maximum number of caudec instances allowed to run concurrently
maxInputFiles=100 # raise a warning and exit if the number of input files is higher than that
preloadSources=false # cache source files to temporary directory (e.g. a fast SSD) before processing them
preventClipping=true # reduce volume to prevent clipping, when resampling or applying gain
setCompilationFlagWithAlbumArtist=false # always true when ALBUMARTIST="Various Artists" regardless of this setting
keepWavMetadata=false # set to true to keep WAV metadata with FLAC and WavPack
tagCompressionSetting=true # store the compression setting in metadata
ignoreUnsupportedFiles=true # set to true to prevent caudec from aborting when some of the input files are unsupported
hashes='' # comma separated list of hashes to compute and tag (CRC32, MD5, SHA1, SHA256 and / or SHA512)
enableColors=true # Enable colors in human-readable output
useBrightColors=true # If enableColors=true, use bright colors (instead of darker ones)

# Whitelist / Blacklist: lists of comma separated tags
# Example: 'artist, date, album, tracknumber, title, genre, replaygain_reference_loudness, replaygain_track_gain, replaygain_track_peak, replaygain_album_gain, replaygain_album_peak'
# Tags in those lists are case-insensitive and format-agnostic.
# Example: 'albumartist' will match both 'ALBUMARTIST' and 'Album Artist'; 'organization' will match 'ORGANIZATION' and 'Label'.

# Current list of tag name variations:
# albumartist <---> album artist
# date <---> year
# description <---> comment
# discnumber <---> disc
# disctotal <---> totaldiscs
# labelno <---> catalog
# location <---> record location
# organization <---> label
# sourcemedia <---> media
# tracknumber <---> track
# tracktotal <---> totaltracks

# tagWhitelist: tags to keep when transcoding (all others are discarded - inactive if empty)
tagWhitelist=''

# tagBlacklist: tags to discard when transcoding (all others are kept - inactive when empty, and when tagWhitelist is non-empty)
tagBlacklist=''
