#!/bin/bash

# Copyright © 2012 - 2026 Guillaume Cocatre-Zilgien <guillaume@cocatre.net>
# https://github.com/gcocatre/caudec
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Global variables =============================================================

declare -r Self_Name='caugain'
declare -r Self_Version='4.7.2'

# Ex_Usage: The command was used incorrectly, e.g., with the wrong number of arguments, a bad flag, a bad syntax in a parameter, or whatever.
# Ex_Data_Err: The input data was incorrect in some way. This should only be used for user's data & not system files.
# Ex_No_Input: An input file (not a system file) did not exist or was not readable. This could also include errors like "No message" to a mailer (if it cared to catch it).
# Ex_No_User: The user specified did not exist. This might be used for mail addresses or remote logins.
# Ex_No_Host: The host specified did not exist. This is used in mail addresses or network requests.
# Ex_Unavailable: A service is unavailable. This can occur if a support program or file does not exist. This can also be used as a catchall message when something you wanted to do doesn't work, but you don't know why.
# Ex_Software: An internal software error has been detected. This should be limited to non-operating system related errors as possible.
# Ex_Os_Err: An operating system error has been detected. This is intended to be used for such things as "cannot fork", "cannot create pipe", or the like. It includes things like getuid returning a user that does not exist in the passwd file.
# Ex_Os_File: Some system file (e.g., /etc/passwd, /etc/utmp, etc.) does not exist, cannot be opened, or has some sort of error (e.g., syntax error).
# Ex_Cant_Create: A (user specified) output file cannot be created.
# Ex_Io_Err: An error occurred while doing I/O on some file.
# Ex_Temp_Fail: temporary failure, indicating something that is not really an error. In sendmail, this means that a mailer (e.g.) could not create a connection, and the request should be reattempted later.
# Ex_Protocol: the remote system returned something that was "not possible" during a protocol exchange.
# Ex_No_Perm: You did not have sufficient permission to perform the operation. This is not intended for file system problems, which should use NOINPUT or CANTCREAT, but rather for higher level permissions.

declare -r Ex_Ok=0            # successful termination
declare -r Ex_Ko=1            # unsuccessful termination
declare -r Ex_Usage=64        # command line usage error
declare -r Ex_Data_Err=65     # data format error
declare -r Ex_No_Input=66     # cannot open input
declare -r Ex_No_User=67      # addressee unknown
declare -r Ex_No_Host=68      # host name unknown
declare -r Ex_Unavailable=69  # service unavailable
declare -r Ex_Software=70     # internal software error
declare -r Ex_Os_Err=71       # system error (e.g., can't fork)
declare -r Ex_Os_File=72      # critical OS file missing
declare -r Ex_Cant_Create=73	# can't create (user) output file
declare -r Ex_Io_Err=74       # input/output error
declare -r Ex_Temp_Fail=75    # temp failure; user is invited to retry
declare -r Ex_Protocol=76     # remote error in protocol
declare -r Ex_No_Perm=77      # permission denied
declare -r Ex_Config_Err=78   # configuration error
declare -r Ex_Interrupt=143   # user interruption (Ctrl+C)

# https://dev.to/ifenna__/adding-colors-to-bash-scripts-48g4

# Clr_El="\\033[2K\\033[0G" # FIXME: can't remember what that does
Clr_Ok="\\033[1;32m" # bright green
Clr_Ko="\\033[1;31m" # bright red
Clr_Wg="\\033[1;33m" # bright yellow

Clr_Rst="\\033[0m" # reset (normal color)

Clr_N_Bk="\\033[0;30m" # black
Clr_B_Bk="\\033[1;30m" # dark gray
Clr_N_Rd="\\033[0;31m" # dark red
Clr_B_Rd="\\033[1;31m" # bright red
Clr_N_Gr="\\033[0;32m" # dark green
Clr_B_Gr="\\033[1;32m" # bright green
Clr_N_Yl="\\033[0;33m" # brown
Clr_B_Yl="\\033[1;33m" # yellow
Clr_N_Bl="\\033[0;34m" # dark blue
Clr_B_Bl="\\033[1;34m" # bright blue
Clr_N_Pp="\\033[0;35m" # dark purple
Clr_B_Pp="\\033[1;35m" # bright purple
Clr_N_Cy="\\033[0;36m" # dark cyan
Clr_B_Cy="\\033[1;36m" # bright cyan
Clr_N_Wh="\\033[0;37m" # bright gray
Clr_B_Wh="\\033[1;37m" # white

for arg in "$@"; do
  if [ "${arg:0:2}" = '--' ]; then
    echo "${Self_Name}: error: try -h" 1>&2
    exit $Ex_Usage
  fi
done

findcmd='find' gnufind='true'
if which 'uname' 1>/dev/null 2>&1 ; then
	OS="$( uname -s )"
	if [ "$OS" = 'Darwin' ]; then
		if which 'gfind' 1>/dev/null 2>&1; then
			findcmd='gfind' gnufind='true'
		fi
	fi
fi

printUsage () {
  echo "$Self_Name ${Self_Version}: compute ReplayGain on multiple directories
Copyright © 2012 - 2026 Guillaume Cocatre-Zilgien
https://github.com/gcocatre/caudec

Usage: $Self_Name DIR(S)
Mass scan albums using caudec to compute ReplayGain. A single directory, or
multiple directories, must be passed as arguments.

-------------------------------------------------------------------------------

Global parameters:

  -h        display this help and exit
  -V        output version information and exit
  -s        be silent, only print to STDOUT what directory is being transcoded,
            and errors to STDERR

  -z        produce machine-parsable output; must be the first parameter on the
            command line to take effect. Run 'caudec -z' on its own to print
            a description of the syntax.

  -Z        produce human-readable output to STDOUT, and machine-parsable
            output to STDERR

-------------------------------------------------------------------------------

For more help, see the online documentation:
https://github.com/gcocatre/caudec"
}

debug () {
	local str="$1"
	echo -e "${Clr_Wg}>>> DEBUG:${Clr_Rst} $str" 1>&2
}

outputWarningOrError () {
  local fileName="$( basename "$path" )"

  if [ ! -f "$fileName" ]; then
    fileName="$path"
  fi

  # processId|status|context|data|message|path
	case "$status" in
		error)
			if [ "$context" = 'processing' ]; then
				str="$( printf "${Clr_B_Bk} * ${Clr_Ko}PR ${Clr_N_Cy}%s${Clr_Rst}\n" "$fileName" )"
			elif [ -n "$path" ]; then
				if [ -n "$message" ]; then
					str="$( printf "${Clr_B_Bk} * ${Clr_Ko}ER ${Clr_N_Cy}%s${Clr_Rst}: %s\n" "$fileName" "$message" )"
				else
					str="$( printf "${Clr_B_Bk} * ${Clr_Ko}ER ${Clr_N_Cy}%s${Clr_Rst}\n" "$fileName" )"
				fi
			elif [ -n "$message" ]; then
				str="$( printf "${Clr_B_Bk} * ${Clr_Ko}ER ${Clr_Rst}%s\n" "$message" )"
			fi
      echo -e "$str" 1>&2
			;;

		warning)
			if [ -n "$path" ]; then
				str="$( printf "${Clr_B_Bk} * ${Clr_Wg}WG ${Clr_N_Cy}%s${Clr_Rst}: %s\n" "$fileName" "$message" )"
			else
				str="$( printf "${Clr_B_Bk} * ${Clr_Wg}WG ${Clr_Rst}%s\n" "$message" )"
			fi
      echo -e "$str" 1>&2
			;;
	esac
}

scanAudioDirectory () {
  local exitCode=$Ex_Ok audioDirectory="$1" OIFS index lastCodec lastDir lastMessage processId status context data
  local message path dir codec files

  if [ "$Self_Verbose" = 'true' ]; then
    if [ "$zParam" != '-z' ]; then
      echo "Scanning \"$audioDirectory\":"
    fi
    caudec $zParam -i -g "$audioDirectory"; exitCode=$?
  else
    echo "$audioDirectory"
    caudec $zParam -s -i -g "$audioDirectory"; exitCode=$?
  fi

  if [ "$Self_Verbose" = 'true' ]; then
    echo
  fi

  return $exitCode
}

findAudioDirectories () {
	local arg="$1"

	if [ "$gnufind" = 'true' ]; then
		$findcmd "$arg" -type f -regextype 'posix-egrep' -regex '.*\.(wav|aiff|caf|flac|wv|ape|mp3|m4a|ogg|opus)$' 2>/dev/null | sed -e 's@/[^/]*\.*$@@' -e 's@^\./@@' | sort -u
	else
		$findcmd -E "$arg" -type f -regex '.*\.(wav|aiff|caf|flac|wv|ape|mp3|m4a|ogg|opus)$' 2>/dev/null | sed -e 's@/[^/]*\.*$@@' -e 's@^\./@@' | sort -u
	fi
}

cleanExit () {
	local exitCode=$1

	exit $exitCode
}

cleanAbort () {
	echo
	echo "$Self_Name: aborting." 1>&2
	kill $( jobs -p ) 1>/dev/null 2>&1
	cleanExit $Ex_Interrupt
}

Self_Verbose='true'
zParam=''

for arg in "$@"; do
  case "$arg" in
    '-h') printUsage ; cleanExit $Ex_Ok ;;
    '-s') Self_Verbose='false' ; shift 1 ;;
    '-V') echo "$Self_Name $Self_Version" ; cleanExit $Ex_Ok ;;
    '-z'|'-Z') zParam="$arg" ;;
    *)
      if [ ! -d "$arg" ]; then
        echo "$Self_Name: error: argument must be a directory (\"$arg\")" 1>&2
        cleanExit $Ex_Usage
      elif [ ! -w "$arg" ]; then
        echo "$Self_Name: error: permission denied, not writable (\"$arg\")" 1>&2
        cleanExit $Ex_Usage
      fi
      ;;
  esac
done

if [ $# -eq 0 ]; then
  printUsage
  cleanExit $Ex_Usage
fi

for signal in INT TERM ABRT PIPE; do
	trap "cleanAbort" $signal
done

declare -a arguments=("$@")
numberOfArguments=${#arguments[@]}
if [ $numberOfArguments -eq 0 ]; then
  echo "$Self_Name: error: at least one directory containing audio files must be provided" 1>&2
  cleanExit $Ex_Usage
fi


exitCode=$Ex_Ok
for (( audioDirIndex=0; audioDirIndex < numberOfArguments; audioDirIndex++ )); do
    audioDirectory="${arguments[$audioDirIndex]}"
    while read audioDirectory; do
      scanAudioDirectory "$audioDirectory"; returnCode=$?
    done < <( findAudioDirectories "$audioDirectory" 2>/dev/null )
done

cleanExit $exitCode
